version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./site1:/var/site1
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - site1

    site1:
        build: docker/php-fpm
        hostname: site1.local
        volumes:
            - ./site1:/var/site1
